<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Make a Transfer</name>
   <tag></tag>
   <elementGuidId>ef16585f-89a7-4121-8fd3-f9a014a9cb4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#childButtonSidebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='childButtonSidebar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97e419a6-67ef-4ef4-aa38-8d7b8c1a0b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>childButtonSidebar</value>
      <webElementGuid>dce67e53-eb2b-4da1-ac99-097b7dfca164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-primary-30 text-white   flex w-full items-center border-l-4 border-secondary-70 py-2 pl-10 pr-2 text-xs font-normal hover:bg-[#05549C] hover:text-secondary-70</value>
      <webElementGuid>8d6a9aa5-6d6f-418c-83ae-98ad09f4bd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/#</value>
      <webElementGuid>7062ef3a-d776-40b6-b7a7-9a8f18894522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Make a Transfer</value>
      <webElementGuid>865fffb3-4083-4a7b-8b61-e0b76ff5a3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;scrollHomeDefault fixed top-16 bottom-0 ml-12 w-52 overflow-hidden bg-[#034186] hover:overflow-y-auto hover:overflow-x-hidden md:flex hidden&quot;]/div[@class=&quot;mt-4 flex w-full flex-col&quot;]/div[@id=&quot;disclosureSideBar&quot;]/div[1]/button[@id=&quot;childButtonSidebar&quot;]</value>
      <webElementGuid>9bc8f8ea-c04f-4c6f-93f2-5df1b333d9a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='childButtonSidebar']</value>
      <webElementGuid>6a7be1e3-aeb2-45ee-8f3a-0790d0785a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='disclosureSideBar']/div/button</value>
      <webElementGuid>e8af421c-cbaf-4c0a-b4d5-eb99f25b1260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRI to Other'])[1]/following::button[1]</value>
      <webElementGuid>b9b75a59-7971-41b5-89a2-3df6b545e8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRI to BRI'])[1]/following::button[2]</value>
      <webElementGuid>e1025aa4-4605-4b39-bd37-37e546babe42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer History'])[1]/preceding::button[1]</value>
      <webElementGuid>998e15f4-d3e0-40d9-bf68-c867a2aa3a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll'])[1]/preceding::button[2]</value>
      <webElementGuid>eacdf8c2-2299-4f6a-acf5-57a1f2a58251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Make a Transfer']/parent::*</value>
      <webElementGuid>7b6a4c8f-8a37-4574-94e1-d5bb0dbc621a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/button</value>
      <webElementGuid>adec2df6-0b4f-4463-8126-e206d056fe98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'childButtonSidebar' and @href = '/#' and (text() = 'Make a Transfer' or . = 'Make a Transfer')]</value>
      <webElementGuid>2cc1cb6d-693f-42c9-a443-9f9502e56194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
