<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Fund Transfer</name>
   <tag></tag>
   <elementGuidId>24fed31d-d08c-4bb3-bc0e-17f92a75b6fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-disclosure-button-:rn:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e81199fb-2695-4dce-ba23-8ec95e2e6d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-disclosure-button-:rn:</value>
      <webElementGuid>83fd1c9e-b6f0-4357-9ba4-d813a07d96b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white hover:bg-primary-50 hover:bg-opacity-40 hover:text-secondary-70 flex h-12 w-full items-center text-xs hover:pl-1</value>
      <webElementGuid>89c46992-4bea-4d33-86cc-39bfefda062b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78d00401-b9da-43cd-be15-444096a7567e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a6bebbc-1132-4648-9498-cae468468048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fund Transfer</value>
      <webElementGuid>d75f83d0-868b-4566-9ab7-008c8726baaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-disclosure-button-:rn:&quot;)</value>
      <webElementGuid>8901535c-ac1c-41b6-b140-3ee54b03cff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-disclosure-button-:rn:']</value>
      <webElementGuid>9a57d1d8-2434-477d-9084-76bbd4f41033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='disclosureSideBar']/dt/button)[6]</value>
      <webElementGuid>866d85ce-29b2-4964-8c51-32e8f8ada924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digi Trade &amp; Guarantee'])[1]/following::button[1]</value>
      <webElementGuid>422b4421-1fb0-41db-b48f-31ca3ebd20d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remittance'])[1]/following::button[2]</value>
      <webElementGuid>48d7bc39-17aa-4b78-bf16-cb63b04028ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investment Transaction'])[1]/preceding::button[1]</value>
      <webElementGuid>5ddad350-6465-45ca-95a7-e0566c85aa51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/dt/button</value>
      <webElementGuid>238b10d1-828d-4c6e-b9c9-6e12b8c790a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-disclosure-button-:rn:' and @type = 'button' and (text() = 'Fund Transfer' or . = 'Fund Transfer')]</value>
      <webElementGuid>5174fa81-0566-4cfb-a1ac-79e9a16ebbc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
