<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BRI to Other</name>
   <tag></tag>
   <elementGuidId>aadeee51-6035-4335-aebb-70106a7137b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-disclosure-button-:rt:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>978d235c-228a-464a-b0a2-80a5a2840a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-disclosure-button-:rt:</value>
      <webElementGuid>b67d054c-16b7-454b-b7e4-808ace187351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white hover:bg-primary-50  hover:bg-opacity-40 hover:text-secondary-70 mt-1 flex h-12 items-center justify-between text-xs hover:pl-1 md:w-full</value>
      <webElementGuid>cdb411b4-e125-4843-9b38-88b0a120178f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b70d964-2469-4633-a940-8066ad3f2f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>43e46bcf-eff7-46f4-a670-6d0b4618f679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BRI to Other</value>
      <webElementGuid>a5b316e1-7793-4833-9124-2cddbb4841ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-disclosure-button-:rt:&quot;)</value>
      <webElementGuid>5277ee27-458d-447c-a8d5-51b4698c866c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-disclosure-button-:rt:']</value>
      <webElementGuid>4ee710c6-dde3-4992-9675-8eb35d6bbe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='disclosureSideBar']/dt/button)[9]</value>
      <webElementGuid>bbd18da8-52c8-4821-a1d7-8847f8f0b0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRI to BRI'])[1]/following::button[1]</value>
      <webElementGuid>3bdea1a4-f33d-44e8-8f8e-bf7bdd1b0e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fund Transfer'])[2]/following::button[2]</value>
      <webElementGuid>6180aa50-2fd1-4932-b25d-87ec3d1b29ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll'])[1]/preceding::button[1]</value>
      <webElementGuid>ffa810a7-9769-498c-9e67-9089cfe2d0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/dt/button</value>
      <webElementGuid>cbdb01a0-3bce-4b8f-bdd0-8d9bca304cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-disclosure-button-:rt:' and @type = 'button' and (text() = 'BRI to Other' or . = 'BRI to Other')]</value>
      <webElementGuid>db08521a-1533-4a25-8929-5089d6dc78c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
