<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CNY_DEBITAMOUNT</name>
   <tag></tag>
   <elementGuidId>5cf7c8b8-e5c9-45e3-8c60-4adbb21236ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbb50381-08cd-459c-a258-60547f02b7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ee70f0e-35ac-48ce-b1dd-832436d34ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>75caddfe-e290-4575-81e7-fbd72fcbb9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAmount</value>
      <webElementGuid>56180a4f-5144-4c52-a4dd-69138c5306a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DEBITAMOUNT</value>
      <webElementGuid>a908f552-0f0d-43a8-97df-8594cc189c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:ring-0.5 block h-8 w-full rounded border-neutral-70  bg-white px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 hover:border-primary-70 focus:border-primary-70 focus:outline-0 focus:ring-primary-70</value>
      <webElementGuid>9d66703a-131d-4eef-81ee-300ee91eb91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>40453c5c-f546-4e52-bff3-13c473ef9c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1,000</value>
      <webElementGuid>2f8e4fc0-2673-46a6-9860-74d63f3714f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;mt-16 w-full overflow-x-hidden md:ml-64  ml-0 min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;mb-24 grid grid-rows-1 gap-4&quot;]/div[@class=&quot;mt-2 grid grid-cols-12 gap-2&quot;]/div[@class=&quot;col-span-7&quot;]/div[@class=&quot;h-full w-full rounded-lg border border-white bg-white p-5&quot;]/div[@class=&quot;flex flex-col space-y-5&quot;]/div[@class=&quot;flex flex-col space-y-1&quot;]/div[@class=&quot;flex w-full&quot;]/input[@id=&quot;inputAmount&quot;]</value>
      <webElementGuid>c741409d-2d50-4ea2-baa2-457214a70fc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAmount']</value>
      <webElementGuid>d5948c2b-00ec-42e1-b4ff-328929800f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div[6]/div/input</value>
      <webElementGuid>2dc46a78-5ec3-4327-a199-9b0ede2ca7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>d907c516-7428-4f8b-9f59-8ce5972ab74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputAmount' and @name = 'DEBITAMOUNT' and @placeholder = '0']</value>
      <webElementGuid>b3a75015-32f1-4189-8919-b8b75c6ff18f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
