<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Beneficiary Name_beneficiaryName</name>
   <tag></tag>
   <elementGuidId>7328ae60-d0b4-4d17-b3ab-ff8cf26fff4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;beneficiaryName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='beneficiaryName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59160e34-a634-4bc7-a3bb-368d4b698c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43beb21f-56ac-4785-83ab-4cd58e440351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white border-neutral-70 hover:border-primary-70 focus:border-primary-70 w-full text-sm h-9 rounded p-1 px-2 border border-grey-80 shadow-sm</value>
      <webElementGuid>7ce0d8b0-3912-4cb9-adef-9edfa2c25e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>beneficiaryName</value>
      <webElementGuid>46eb4dc3-57e6-424e-bfc3-368c03915128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9e74f165-b568-4ee2-bc59-f67aa76ab5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;mt-16 w-full overflow-x-hidden md:ml-64  ml-0 min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/section[@class=&quot;mt-6&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md&quot;]/div[2]/form[1]/div[@class=&quot;bg-primary-99 rounded border border-grey-80 p-4 mb-6&quot;]/div[@class=&quot;grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4&quot;]/div[@class=&quot;relative inline-block&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white border-neutral-70 hover:border-primary-70 focus:border-primary-70 w-full text-sm h-9 rounded p-1 px-2 border border-grey-80 shadow-sm&quot;]</value>
      <webElementGuid>797d7a7c-3597-4413-8c4c-107403d00f97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='beneficiaryName']</value>
      <webElementGuid>5e038f72-a112-4428-8cb7-c5ab3a6abb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/section[2]/div/div[2]/form/div/div/div[6]/div/input</value>
      <webElementGuid>7e466710-af2a-4ae0-bf61-341a501a6941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>2032c42e-b1bf-446d-a5aa-64ad3b794546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'beneficiaryName']</value>
      <webElementGuid>23a8434a-cd9a-4a1f-af32-566409f808d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
