<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank CodeSWIFT Code_headlessui-combobox-input-r15</name>
   <tag></tag>
   <elementGuidId>a1c4f2a8-4c0b-4e3d-8b47-cffd8c1de444</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-:r15:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e26afeb-462a-4b0a-9c82-37f6a33a2217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white block w-full border-neutral-70 text-[0.8125rem] h-8 px-2 rounded transition-all caret-primary-70 placeholder:text-neutral-40 focus:ring-0.5 focus:ring-primary-70 focus:outline-0 shadow-sm hover:border-primary-70 focus:border-primary-70 disabled:bg-grey-90 disabled:cursor-not-allowed</value>
      <webElementGuid>919396d3-6162-4aa1-8189-91162b35f3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-:r15:</value>
      <webElementGuid>f41e1b57-e343-4263-a526-a66386193192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>39e12ba0-19d8-4c44-b646-5867fa69b094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29a03905-3994-47d5-a9f3-5d888db9a20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b169825e-7df6-401f-9a75-da6771d1e527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-:r15:&quot;)</value>
      <webElementGuid>48271495-0343-4aed-b978-de4f875cdbbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-:r15:']</value>
      <webElementGuid>16d2758d-ee28-4be8-827b-0d9629c3fb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>652faeb9-d818-4005-bdfd-911e0d1093ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/input</value>
      <webElementGuid>4cfdb09f-b9a6-4806-857d-1dd2f400872f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-:r15:' and @type = 'text']</value>
      <webElementGuid>478ddc23-1887-4883-ae23-4178abc9a459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
