<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Deposit Name_depositoName</name>
   <tag></tag>
   <elementGuidId>48140022-cb54-410b-8ff8-82e08d732545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;depositoName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[3]/div/main/div[4]/div[2]/form/div/div[1]/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f708be89-de4f-498a-b6aa-27629914162c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0b41c01-6a84-46b0-8cba-f427b1e4f773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>depositoName</value>
      <webElementGuid>35dde440-53bb-43a8-9e62-cac14a04ee6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> focus:ring-1 hover:ring-primary-70  focus:ring-primary-70 focus:border-primary-70  block sm:text-sm border-neutral-70 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed</value>
      <webElementGuid>9a5c8b82-dbc8-4557-a12f-be42c405a780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;relative w-full overflow-x-hidden md:ml-64  ml-0 h-[calc(100vh-64px)] top-16 bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md&quot;]/div[2]/form[1]/div[@class=&quot;bg-primary-99 rounded border border-grey-80 p-4 mb-6&quot;]/div[@class=&quot;grid grid-cols-2 gap-4 md:grid-cols-4&quot;]/div[2]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-1 hover:ring-primary-70  focus:ring-primary-70 focus:border-primary-70  block sm:text-sm border-neutral-70 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed&quot;]</value>
      <webElementGuid>38e035ea-8eeb-4534-b05c-595b7824477c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='depositoName']</value>
      <webElementGuid>3f41c316-d039-449a-8e70-a1270d73a89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div[4]/div[2]/form/div/div/div[2]/div/input</value>
      <webElementGuid>a11325a5-6dfb-4243-b184-4a70ed02b814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>53731121-82b7-41e8-b4ff-cc10dada274c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'depositoName']</value>
      <webElementGuid>33417a17-82ca-4f6f-904d-74c91e466255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
