<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select deposit type</name>
   <tag></tag>
   <elementGuidId>981a98c5-ecca-4cb7-97ed-54e6553f6bde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[3]/div/main/div[4]/div[2]/form/div/div[1]/div[5]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;depositType&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'depositType' and @placeholder = 'Placeholder' and (text() = 'AllAuto Roll-Over (ARO)Non Auto Roll-OverAuto Roll-Over Combo' or . = 'AllAuto Roll-Over (ARO)Non Auto Roll-OverAuto Roll-Over Combo')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>075c5c47-3ac3-4ec2-a237-e716c28a4701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>depositType</value>
      <webElementGuid>a3dd5558-17b7-4d52-88f4-bb89fce26706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-1 h-8 w-full rounded border-grey-80 bg-white p-1</value>
      <webElementGuid>13a72e2c-c513-41ec-9eeb-fbe759394cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Placeholder</value>
      <webElementGuid>f2aed66a-d281-4bdb-a6ec-c6cb749f3845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllAuto Roll-Over (ARO)Non Auto Roll-OverAuto Roll-Over Combo</value>
      <webElementGuid>a77f1945-f173-4268-bf45-3de05dd6990d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;relative w-full overflow-x-hidden md:ml-64  ml-0 h-[calc(100vh-64px)] top-16 bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md&quot;]/div[2]/form[1]/div[@class=&quot;bg-primary-99 rounded border border-grey-80 p-4 mb-6&quot;]/div[@class=&quot;grid grid-cols-2 gap-4 md:grid-cols-4&quot;]/div[5]/select[@class=&quot;mx-1 h-8 w-full rounded border-grey-80 bg-white p-1&quot;]</value>
      <webElementGuid>6345284a-7dd6-4d4f-bb02-a5daeab26efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='depositType']</value>
      <webElementGuid>d662a004-affd-41f5-b7e9-c18cd082fafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div[4]/div[2]/form/div/div/div[5]/select</value>
      <webElementGuid>ad3e2418-1909-41f2-ae64-639fbc122228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit Type'])[1]/following::select[1]</value>
      <webElementGuid>04699f57-b7a9-4bd1-abb6-0242242677c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenor/Terms'])[1]/following::select[2]</value>
      <webElementGuid>9de35676-2496-4059-b0dc-1744357e1adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>9810a3f6-0484-40bd-9d3d-d8a1ebcee670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Created'])[1]/preceding::select[2]</value>
      <webElementGuid>c56a407b-7083-4601-9e5f-416a16ffe9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>f02cf1f5-fc68-407b-aa86-9be814cfabfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'depositType' and @placeholder = 'Placeholder' and (text() = 'AllAuto Roll-Over (ARO)Non Auto Roll-OverAuto Roll-Over Combo' or . = 'AllAuto Roll-Over (ARO)Non Auto Roll-OverAuto Roll-Over Combo')]</value>
      <webElementGuid>e19649be-3729-4eb0-bd0d-94d6c88165c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
