<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Make a Transfer</name>
   <tag></tag>
   <elementGuidId>b29c41fd-ad28-4603-9141-ca48336828a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#childButtonSidebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='childButtonSidebar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>677dc20d-cf56-4216-bcd5-2ce54f0746dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>childButtonSidebar</value>
      <webElementGuid>91e4934e-fdaf-4684-a8d3-16f6492eeda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-primary-30 text-white   flex w-full items-center border-l-4 border-secondary-70 py-2 pl-10 pr-2 text-xs font-normal hover:bg-[#05549C] hover:text-secondary-70</value>
      <webElementGuid>7c96048a-7144-42a6-be76-a2d43cc083e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/#</value>
      <webElementGuid>952e0b10-7b3a-4f87-9b70-462753f2bc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Make a Transfer</value>
      <webElementGuid>1bca9f27-2b4a-486b-97b0-14e4e81b1163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;scrollHomeDefault fixed top-16 bottom-0 ml-12 w-52 overflow-hidden bg-[#034186] hover:overflow-y-auto hover:overflow-x-hidden md:flex hidden&quot;]/div[@class=&quot;mt-4 flex w-full flex-col&quot;]/div[@id=&quot;disclosureSideBar&quot;]/div[1]/button[@id=&quot;childButtonSidebar&quot;]</value>
      <webElementGuid>b0e3457c-b1ed-4719-8e12-20365115de65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='childButtonSidebar']</value>
      <webElementGuid>6f7b7de2-2dc8-4d77-ab96-f8e4d689dd69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='disclosureSideBar']/div/button</value>
      <webElementGuid>f378c335-0277-49c1-8f93-57494d205894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRI to Other'])[1]/following::button[1]</value>
      <webElementGuid>b606c72f-5638-4e6f-b0b2-ccf702f51f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRI to BRI'])[1]/following::button[2]</value>
      <webElementGuid>91694101-ef6a-4237-818c-335e87c39275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer History'])[1]/preceding::button[1]</value>
      <webElementGuid>c70ae83d-2094-408c-977c-945538c05d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll'])[1]/preceding::button[2]</value>
      <webElementGuid>8ce395e3-82af-4763-9294-870308cd5f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Make a Transfer']/parent::*</value>
      <webElementGuid>621f4855-d99f-420f-8a54-b30de3647e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/button</value>
      <webElementGuid>9dd9101a-294a-4408-b2c4-310e348c587e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'childButtonSidebar' and @href = '/#' and (text() = 'Make a Transfer' or . = 'Make a Transfer')]</value>
      <webElementGuid>608d34e4-ac46-4a09-adba-79d0ee4f0692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
