<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_focusring-1 hoverring-danger_1ac90e</name>
   <tag></tag>
   <elementGuidId>dffed12f-3c18-4050-a808-e33e0f6df126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Nsel@1234']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea217d20-dd98-4a69-a67e-3ad6f4e68217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4918136f-1f12-497d-a856-c1299117be93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> focus:ring-1 hover:ring-danger-60 focus:ring-danger-60 focus:border-danger-60 block sm:text-sm border-danger-60 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed</value>
      <webElementGuid>2cdfe4cf-fbff-4fbb-8922-d02b43bd5845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>******</value>
      <webElementGuid>873aad37-e354-4612-9a98-6d1eafb0225f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Nsel@1234</value>
      <webElementGuid>bab5af47-86c7-406f-ad97-b0a17e31eb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;w-full h-screen bg-primary-50 flex flex-col justify-center items-center p-4 overflow-y-auto&quot;]/div[@class=&quot;w-full sm:w-96 h-[424px] bg-white rounded mx-auto px-8 py-8 shadow-md&quot;]/form[1]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-1 hover:ring-danger-60 focus:ring-danger-60 focus:border-danger-60 block sm:text-sm border-danger-60 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed&quot;]</value>
      <webElementGuid>312ea408-785a-4299-bfdc-00015c693ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Nsel@1234']</value>
      <webElementGuid>8908078c-3123-4468-a3cb-5aa7271ee135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/form/div[2]/div/input</value>
      <webElementGuid>2092f707-eb2b-4ff2-8563-5ae20426a155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>eb549ff8-4136-493f-bdb8-654c2ea69c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '******']</value>
      <webElementGuid>7a024b8d-aba7-4f9b-a093-c01db766294c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
