<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank CodeSWIFT Code_headlessui-combob_653417</name>
   <tag></tag>
   <elementGuidId>ba721658-f0aa-4062-9f32-b88719aa001e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-:r15:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64fc6847-1b9b-4767-9634-96f312f770e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white block w-full border-neutral-70 text-[0.8125rem] h-8 px-2 rounded transition-all caret-primary-70 placeholder:text-neutral-40 focus:ring-0.5 focus:ring-primary-70 focus:outline-0 shadow-sm hover:border-primary-70 focus:border-primary-70 disabled:bg-grey-90 disabled:cursor-not-allowed</value>
      <webElementGuid>e957552c-769d-476b-a3c8-48f659b3008f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-:r15:</value>
      <webElementGuid>3386150d-d2c4-461e-b5c0-5352b55c929d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>9ff57244-26d7-4091-b8a8-53c1c97e0668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28fa2642-1912-4624-8076-37c8aabf11f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9b8e3e8-0cbb-442f-86b7-5813c490d6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>c52e6c67-c171-4791-8adc-321505313ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>headlessui-combobox-options-:r17:</value>
      <webElementGuid>4f09840d-11f6-403f-ae8b-060f90dedb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>headlessui-combobox-option-:r18:</value>
      <webElementGuid>01d432e7-3e8b-4436-abc5-a38ad92a4cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-:r15:&quot;)</value>
      <webElementGuid>bc91cc77-5438-4c1a-b4a3-1bd8b977aca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-:r15:']</value>
      <webElementGuid>b6366c76-eb4b-4793-8fff-bc04f515f7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>df3ed452-9d07-4aae-9bbc-2c9c67ed108a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/input</value>
      <webElementGuid>ae7f12a8-e63e-4776-a78d-8ddd895507e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-:r15:' and @type = 'text']</value>
      <webElementGuid>0bf52067-83e4-4b24-855f-d91ce1a545b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
