<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_USD_DEBITAMOUNT</name>
   <tag></tag>
   <elementGuidId>1c49639d-8a76-447f-b9e2-f9ea081b3f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec876661-b219-48f8-8372-2936b8a2adb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>845b76e9-2c90-49fc-bc83-cd3b8edcce2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>7b28fbbc-1119-43e6-9c0a-c4600f3d391e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAmount</value>
      <webElementGuid>b967d975-6421-4ea6-af47-a8ace90679bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DEBITAMOUNT</value>
      <webElementGuid>d2d293a6-fe77-45a1-bf1a-64d207bd8ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white block w-full text-[0.8125rem] h-8 px-2  rounded transition-all caret-primary-70 placeholder:text-neutral-40 focus:ring-0.5 focus:ring-primary-70 focus:outline-0 shadow-sm border-neutral-70 hover:border-primary-70 focus:border-primary-70</value>
      <webElementGuid>4df3ab97-635d-4fe8-9969-5756c11e0a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>919980f5-ce64-4e27-88e0-032a489f03fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;mt-16 w-full overflow-x-hidden md:ml-64  ml-0 min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;grid grid-rows-1 gap-4 mb-24&quot;]/div[@class=&quot;grid grid-cols-12 gap-2 mt-2&quot;]/div[@class=&quot;col-span-7&quot;]/div[@class=&quot;border border-white bg-white w-full h-full p-5 rounded-lg&quot;]/div[@class=&quot;flex flex-col space-y-5&quot;]/div[@class=&quot;flex flex-col space-y-1&quot;]/div[@class=&quot;flex w-full&quot;]/input[@id=&quot;inputAmount&quot;]</value>
      <webElementGuid>962a4e58-6107-42e9-89f2-b16c688cc65c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAmount']</value>
      <webElementGuid>2ad345ac-48e7-415d-aafb-3b4883484429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div[6]/div/input</value>
      <webElementGuid>cbb8abf6-6c82-4068-88b0-bc1ef1a805ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>72b5d7bb-a2d6-4cf8-ad2d-80a2e67d1fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputAmount' and @name = 'DEBITAMOUNT' and @placeholder = '0']</value>
      <webElementGuid>1dae8471-d367-408d-857a-7c0bc43ef05f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
