<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>724f4287-fa05-488e-8a31-48c86bf2d856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>ea5c27f4-e534-4296-acf9-aeb55c51cc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M12 14l-4-4h8z</value>
      <webElementGuid>5e39587a-0782-45c9-8b7b-27fb86b720c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-button-:r16:&quot;)/svg[@class=&quot;h-6 w-6 text-gray-40&quot;]/g[1]/path[2]</value>
      <webElementGuid>b451f53b-4d23-4bc5-a3c1-d78b08647f87</webElementGuid>
   </webElementProperties>
</WebElementEntity>
