<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CENAIDJAXXX</name>
   <tag></tag>
   <elementGuidId>d2bf7448-0c5c-428e-95eb-ee990e9277d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-combobox-option-:r19:']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>81bdad99-2812-4ce6-b3cb-da151973ef6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block truncate font-normal</value>
      <webElementGuid>53bc6c50-06bf-43a9-8bc2-5e4741995b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CENAIDJAXXX</value>
      <webElementGuid>11db6278-e856-4cf6-b876-fece79b29d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-:r19:&quot;)/span[@class=&quot;block truncate font-normal&quot;]</value>
      <webElementGuid>272d2b33-e5bf-44e6-8b42-eabe0a28fcf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-:r19:']/span</value>
      <webElementGuid>97f13a56-dc4f-4dfd-abd1-b7f96a419f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CENAHKHRXXX'])[1]/following::span[1]</value>
      <webElementGuid>b5a65d82-47b8-4272-8026-fe2e638488c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Code/SWIFT Code'])[1]/following::span[2]</value>
      <webElementGuid>c4d09127-0220-4c1f-a2f0-8b4d5017571e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiary Bank'])[1]/preceding::span[1]</value>
      <webElementGuid>9e827163-2509-4c24-8337-6c2ac8e72de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/preceding::span[3]</value>
      <webElementGuid>d58b36a6-c16f-4847-81eb-49615ba3a64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CENAIDJAXXX']/parent::*</value>
      <webElementGuid>de8e933e-3337-411c-9274-a86961502971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>bc47fc87-a609-459f-8d23-4545c142e20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CENAIDJAXXX' or . = 'CENAIDJAXXX')]</value>
      <webElementGuid>def9d7f5-39b7-4632-b28d-c6ddf61bd769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
