<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_District 7</name>
   <tag></tag>
   <elementGuidId>7a21b4ab-7ec0-4145-9a60-93073fd9610b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BENEFICIARYADDRESS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='BENEFICIARYADDRESS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>31d502b7-14e0-428f-8570-5dc1f1357612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BENEFICIARYADDRESS</value>
      <webElementGuid>938527ee-2819-43cb-a7f2-f236ab65b479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BENEFICIARYADDRESS</value>
      <webElementGuid>50ade08b-08bb-457d-9d09-e98ca5c75929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-neutral-60 focus:ring-primary-70 focus:ring-0.5 focus:border-primary-70 focus:outline-0 hover:border-primary-70</value>
      <webElementGuid>be10e0bb-6e4d-427b-932a-971e60a964c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g., 2076 Ryder Avenue, Bellevue</value>
      <webElementGuid>fc7fdaf4-8670-4c26-8ee7-b3533fe7395c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8fe09667-780b-4b1b-9984-e00b1c01f05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>District 7</value>
      <webElementGuid>c4378cb7-059b-4833-8309-9620a613a0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BENEFICIARYADDRESS&quot;)</value>
      <webElementGuid>1068ab35-10e8-4ffd-bebf-ce6b42ab9253</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='BENEFICIARYADDRESS']</value>
      <webElementGuid>105929df-8156-46c3-b8f8-c4de3fccec3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div/div[10]/textarea</value>
      <webElementGuid>4a3392ad-b656-4755-aa74-49319c47b04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::textarea[1]</value>
      <webElementGuid>d2d5a760-56a0-4e88-86c1-23c1cdf87a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United Kingdom'])[1]/following::textarea[1]</value>
      <webElementGuid>22ee866e-b862-483e-ba60-1c50c871ec16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(10/50) characters used'])[1]/preceding::textarea[1]</value>
      <webElementGuid>634608a9-74ca-4fec-b233-62e806eed3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::textarea[1]</value>
      <webElementGuid>068c8a84-865a-4f50-9def-c60413733213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='District 7']/parent::*</value>
      <webElementGuid>ed6b3b22-5649-46d8-ba94-f70ec6d3d65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f667a63b-4e57-4093-97bc-c86a0024dada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'BENEFICIARYADDRESS' and @id = 'BENEFICIARYADDRESS' and @placeholder = 'e.g., 2076 Ryder Avenue, Bellevue' and (text() = 'District 7' or . = 'District 7')]</value>
      <webElementGuid>c0ab90e8-2d23-4b63-8f5d-26206c9b886c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
