<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Distri</name>
   <tag></tag>
   <elementGuidId>a1a6dc69-d00a-49fa-b73f-0b65e5d2ac10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BENEFICIARYADDRESS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='BENEFICIARYADDRESS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c924f16f-3e17-4959-97ea-8a996d0ec2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BENEFICIARYADDRESS</value>
      <webElementGuid>02acd4b3-f0f0-4170-a83b-832bb8ac6a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BENEFICIARYADDRESS</value>
      <webElementGuid>69ad04ac-b92e-4ffb-b8de-68ee09f774e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-neutral-60 focus:ring-primary-70 focus:ring-0.5 focus:border-primary-70 focus:outline-0 hover:border-primary-70</value>
      <webElementGuid>0ef0be64-e15b-4685-988a-c4b15d7adcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g., 2076 Ryder Avenue, Bellevue</value>
      <webElementGuid>160c77a9-a4c1-429a-9c79-42c2cf494374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4a18d6f4-cd47-4fe5-ae68-daa9b5a1b185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Distri</value>
      <webElementGuid>a4b46f4d-1ebc-4d01-a28e-ca90ebda58a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BENEFICIARYADDRESS&quot;)</value>
      <webElementGuid>a92330a9-24c7-4d2e-ab71-163d9e3b8982</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='BENEFICIARYADDRESS']</value>
      <webElementGuid>7e803c91-20dc-485c-9295-098b0f21b667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div/div[10]/textarea</value>
      <webElementGuid>a9c0fe27-4e01-45a9-ae65-cabd8af475ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::textarea[1]</value>
      <webElementGuid>eee3c627-fe4a-4125-83e5-4e3913f5d559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United Kingdom'])[1]/following::textarea[1]</value>
      <webElementGuid>7099d865-5f00-401b-87bd-1fcfa727c34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(6/50) characters used'])[1]/preceding::textarea[1]</value>
      <webElementGuid>6d9c60c4-4205-4582-9b15-3bb102f19ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::textarea[1]</value>
      <webElementGuid>9c68b0e7-c01f-4e45-bd03-88cc43fdc30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Distri']/parent::*</value>
      <webElementGuid>1ea999af-868d-439a-b390-0b3b36e049f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>51a6f6a7-4082-48b3-84bc-13597d7b3dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'BENEFICIARYADDRESS' and @id = 'BENEFICIARYADDRESS' and @placeholder = 'e.g., 2076 Ryder Avenue, Bellevue' and (text() = 'Distri' or . = 'Distri')]</value>
      <webElementGuid>71d509bc-ee7c-4f90-8c87-108d8b87f1ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
