<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Distr</name>
   <tag></tag>
   <elementGuidId>ca0273ef-9643-45ed-8ce1-8f4fc1b70d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BENEFICIARYADDRESS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='BENEFICIARYADDRESS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>73353ff0-c6bb-49e4-bf33-71f7b24d0f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BENEFICIARYADDRESS</value>
      <webElementGuid>62d64d66-9c03-49bd-9655-ad058c53cb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BENEFICIARYADDRESS</value>
      <webElementGuid>bcdb19b2-0c66-4cf3-80ae-d998ae662ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-neutral-60 focus:ring-primary-70 focus:ring-0.5 focus:border-primary-70 focus:outline-0 hover:border-primary-70</value>
      <webElementGuid>a00defa1-119a-478e-9b3e-11e9b3ec162f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g., 2076 Ryder Avenue, Bellevue</value>
      <webElementGuid>6006fede-1d50-423c-95cd-96675abb8c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7fc42770-414d-4269-b22e-ba1dcf6a8353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Distr</value>
      <webElementGuid>734352ec-c507-4200-afa9-4cc2de172815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BENEFICIARYADDRESS&quot;)</value>
      <webElementGuid>433a2ad9-c1da-4ca6-8dc2-d2ad5d5fd032</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='BENEFICIARYADDRESS']</value>
      <webElementGuid>ed871f21-bba1-4f20-a212-fa0912a1e0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div/div[10]/textarea</value>
      <webElementGuid>734cb2bd-fbac-4528-bbb7-3106abeda38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::textarea[1]</value>
      <webElementGuid>13f9ca67-17ba-4e97-84ba-cf619ca424a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United Kingdom'])[1]/following::textarea[1]</value>
      <webElementGuid>c72e741d-454d-4fb0-9749-ebdbb2d178e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(5/50) characters used'])[1]/preceding::textarea[1]</value>
      <webElementGuid>862be0e6-13be-4a82-b2c7-4f9a32e34e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::textarea[1]</value>
      <webElementGuid>abe12c9d-5903-432f-a41a-8f9b7d44295d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Distr']/parent::*</value>
      <webElementGuid>37aa23a6-d458-4c69-9d65-f1f9df7b2c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8eceb8b7-3a8c-4882-9d2e-3561878e3fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'BENEFICIARYADDRESS' and @id = 'BENEFICIARYADDRESS' and @placeholder = 'e.g., 2076 Ryder Avenue, Bellevue' and (text() = 'Distr' or . = 'Distr')]</value>
      <webElementGuid>6537c5bd-387d-4408-af69-f97933154bea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
