<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDR_amount</name>
   <tag></tag>
   <elementGuidId>48d20453-e887-4608-8c3d-a93c0ec366ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d741277e-89b3-41b2-98f5-23a346b7658d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 my-auto w-full border-none text-base font-semibold leading-5 disabled:bg-neutral-90</value>
      <webElementGuid>a36c3446-407c-4bc9-915e-160607cb74c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>18d6c69f-f955-4fd2-be3d-ef0b45f172a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>85491467-a7e7-4884-b9aa-f2b27b388491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAmount</value>
      <webElementGuid>d7e73c0b-a7b8-4bdd-b518-cd17646553d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d43eacd-6008-4af9-987d-273c778ae2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>47936a1d-5e41-4569-94a2-8b4bda9dfeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAmount&quot;)</value>
      <webElementGuid>8e96023b-ec7c-4980-99eb-e5a8156226ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAmount']</value>
      <webElementGuid>b31c2479-1fc1-4d5e-bc8a-51e044b0f6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[4]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>85104c4b-4c51-4291-975b-616b1a63793f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>01fe63ec-fda1-4c34-ad89-ae1c381f7a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Amount' and @name = 'amount' and @id = 'inputAmount' and @type = 'text']</value>
      <webElementGuid>aa0df7e4-0576-4f4e-95b5-1fefb3e6a29c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
