<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ARO_COMBO</name>
   <tag></tag>
   <elementGuidId>570253db-b2db-491e-ace5-895b4d81d4a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Non-ARO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Add On']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @id = 'Non-ARO' and @name = 'deposit_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ae6734b-39c5-4902-bd39-3fb7aab67051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b494e6bf-ac6b-43eb-881f-2a91e5a064db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Non-ARO</value>
      <webElementGuid>856d056e-0764-4715-81fb-e90da6ec1562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deposit_type</value>
      <webElementGuid>54ff0867-0f33-4ab1-a96c-099ed6de9b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>a26b0b7a-6a53-4eaa-828d-2b3ff633aa7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Non Auto Roll-Over</value>
      <webElementGuid>9c6b8f72-a74a-44bb-8637-bc3cc1591e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Non-ARO&quot;)</value>
      <webElementGuid>cf0e659d-0afa-47ab-8324-79bf8dc2cea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Non-ARO']</value>
      <webElementGuid>8a45ad6d-f78d-4ee6-a5fd-8762dd84b1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[4]/div/div/div/div[4]/div[2]/input</value>
      <webElementGuid>92ea3d87-e21f-4e8f-94a4-6e40e1e98620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>744ad4fa-cfb0-474c-b15d-b7e41583b46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Non-ARO' and @name = 'deposit_type']</value>
      <webElementGuid>77fbbecf-5652-4291-8fb1-5ba3c721c28d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
