<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drop down Select Frequency Recurring</name>
   <tag></tag>
   <elementGuidId>7110a087-9192-44e5-9478-a043f3bbd3e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Frequency'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.react-select__input-container.css-vwja0k</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>661cbe0f-f5ac-4ec9-87f5-c3d2ba168066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__input-container css-vwja0k</value>
      <webElementGuid>b95580b3-6635-40d3-9c9f-722b2276e710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>`</value>
      <webElementGuid>218b9ddb-f21f-4b74-8586-b7f17ea8710d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;relative w-full overflow-x-hidden md:ml-64  ml-0 h-[calc(100vh-64px)] top-16 bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;relative&quot;]/section[@class=&quot;space-y-6&quot;]/div[2]/div[1]/form[1]/div[@class=&quot;grid grid-cols-3 gap-6 lg:grid-cols-6 xl:grid-cols-5&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md col-span-3 flex flex-col space-y-4&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;relative flex space-x-3 pt-3.5 pl-7 before:absolute before:left-1.5 before:top-0 before:h-14 before:w-4 before:border-l before:border-b before:border-[#BDBDBD]&quot;]/div[@class=&quot;flex w-full flex-col space-y-4&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;react-select__container css-b62m3t-container&quot;]/div[@class=&quot;react-select__control react-select__control--is-focused react-select__control--menu-is-open css-1pahdxg-control&quot;]/div[@class=&quot;react-select__value-container css-1d8n9bt&quot;]/div[@class=&quot;react-select__input-container css-vwja0k&quot;]</value>
      <webElementGuid>e31bb920-3a69-4985-bc2a-669af3620c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/section/div[2]/div/form/div/div/div[5]/div[4]/div/div/div/div/div/div</value>
      <webElementGuid>0d3d6578-83c8-4c44-83f5-5f94f54d4449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequency'])[1]/following::div[4]</value>
      <webElementGuid>4217c73a-18f8-4f77-ad81-d5b84c40eff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::div[12]</value>
      <webElementGuid>3c90b53f-94c8-4a39-82ec-f79532872cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No options'])[1]/preceding::div[1]</value>
      <webElementGuid>0d7fd097-4fd1-4265-babd-c8960c66fffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Period'])[1]/preceding::div[4]</value>
      <webElementGuid>a26b3e19-1809-4be6-85e5-9f0026df5996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div</value>
      <webElementGuid>dfb64eeb-4dbf-4307-8b1a-7b0aff24aafe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
