<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start PeriodRecurring</name>
   <tag></tag>
   <elementGuidId>f03aa53f-f35c-430b-b793-62c472d4d473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[3]/div/main/div/section/div[2]/div/form/div/div[1]/div[3]/div[4]/div/div[2]/div[1]/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f12a077-fedd-40d1-aac3-63f56bbb866e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50f178b9-11a1-46c1-bb2e-f8d0a047b3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>9bf1b325-5b56-4f21-a1eb-d7b0159f414b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium text-sm w-full text-sm px-2 border border-grey-80 rounded disabled:bg-neutral-80 disabled:cursor-disabled w-full text-[0.8125rem] px-2 border border-grey-80 shadow-sm react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>6e916a0a-2e78-489f-8b23-1b804929bc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;mt-16 w-full overflow-x-hidden md:ml-64  ml-0 min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;relative&quot;]/section[@class=&quot;space-y-6&quot;]/div[2]/div[1]/form[1]/div[@class=&quot;grid grid-cols-3 md:grid-cols-6 xl:grid-cols-5  gap-6&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md flex flex-col col-span-3 space-y-4&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;flex pt-3.5 pl-7 relative space-x-3 before:w-4 before:h-14 before:border-[#BDBDBD] before:border-l before:border-b before:absolute before:left-1.5 before:top-0&quot;]/div[@class=&quot;flex flex-col space-y-4 w-full&quot;]/div[@class=&quot;flex space-x-4&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;react-datepicker-wrapper bg-black&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/input[@class=&quot;font-medium text-sm w-full text-sm px-2 border border-grey-80 rounded disabled:bg-neutral-80 disabled:cursor-disabled w-full text-[0.8125rem] px-2 border border-grey-80 shadow-sm react-datepicker-ignore-onclickoutside&quot;]</value>
      <webElementGuid>1ff87489-ff8d-4b78-8f53-28e27a04f8b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>d384696e-0724-47bb-b75c-c0aac072043a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/section/div[2]/div/form/div/div/div[3]/div[4]/div/div[2]/div/div/div/input</value>
      <webElementGuid>81983478-6872-4b78-af02-823547cf4b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>48b07abe-8435-4955-b92a-2d7203bec8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>fcb92913-7bda-462e-b6c1-b17f9935f579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
