<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description Remark</name>
   <tag></tag>
   <elementGuidId>c2d231c9-1302-40cf-840d-6239b75f2c93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-:r4i:']/div[2]/div[2]/div[2]/div[2]/div[2]/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ad7fceae-85b0-43ab-8383-1cc2a69139b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>89809d25-58f9-42a9-92ee-126cda1652de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:border-primary-70 border-grey-70 rounded text-sm w-full disabled:bg-[#eeeeee] disabled:border-[#e6e6e6]</value>
      <webElementGuid>21cca4a4-4d94-4349-a4fc-22f685c7efd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>57291dac-3fff-4190-99d8-b0417625d422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>`</value>
      <webElementGuid>d28efeb8-b3f2-4df6-a5bb-3f2ac528a67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-:r4i:&quot;)/div[@class=&quot;absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 min-w-120 bg-white p-8 shadow-md rounded text-sm w-10 overflow-hidden rounded-md opacity-100 scale-100&quot;]/div[@class=&quot;flex h-full flex-col justify-between&quot;]/div[@class=&quot;py-4&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;w-3/4&quot;]/textarea[@class=&quot;focus:border-primary-70 border-grey-70 rounded text-sm w-full disabled:bg-[#eeeeee] disabled:border-[#e6e6e6]&quot;]</value>
      <webElementGuid>71ba09ee-5084-4aef-aee3-4c507869f4c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-:r4i:']/div[2]/div[2]/div[2]/div[2]/div[2]/textarea</value>
      <webElementGuid>c50a8759-21d2-42e8-ba3b-ca8447fa6953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description / Remark'])[1]/following::textarea[1]</value>
      <webElementGuid>39258fc8-08e6-4d49-920f-1fddbc5a23fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Others'])[1]/following::textarea[1]</value>
      <webElementGuid>96dba684-4c42-4860-bfda-91eb201f151e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>57cae5b4-869a-4494-9683-0b12bc9d3eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Task for Rework'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b7a5afd3-4495-4924-9b4a-ce99802b65e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c13c7fe8-3aec-4b99-886f-80e66f126d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = '`' or . = '`')]</value>
      <webElementGuid>4e60d35e-f851-446e-84b4-ea3f06b34e32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
