<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukan OTP_otp-code</name>
   <tag></tag>
   <elementGuidId>9925fc84-8d97-4280-8ad1-9f1c65099571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otp-code']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'password' and @autocomplete = 'otp-code' and @name = 'otp-code' and @placeholder = 'Enter OTP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otp-code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fd10f93-bf74-4d9e-b3be-dbd93dd5c4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fd65ccbf-8749-4208-b221-2bb52b8f4796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white pr-8 border-neutral-70 hover:border-primary-70 focus:border-primary-70 h-auto text-sm hover:border-primary-70 focus:border-primary-70 border-neutral-70 w-full</value>
      <webElementGuid>747b99e9-bfee-446c-bd48-1850e4c916ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a34141fa-8023-4c62-b39f-2f73709f66be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>otp-code</value>
      <webElementGuid>ade4a958-3aa2-40f8-ad11-8b899351a11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp-code</value>
      <webElementGuid>0d9cd049-1c88-4d16-af26-8f63a6786a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter OTP</value>
      <webElementGuid>6e30a841-af80-4f16-95bb-fd10f7cc9a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>cd1f1e72-4244-4178-879c-acd240923eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>71879d82-b346-42b3-9a20-4bc5d8a473d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-form&quot;)/div[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;w-3/5 flex-col&quot;]/div[@class=&quot;relative inline-block w-full&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white pr-8 border-neutral-70 hover:border-primary-70 focus:border-primary-70 h-auto text-sm hover:border-primary-70 focus:border-primary-70 border-neutral-70 w-full&quot;]</value>
      <webElementGuid>bb5aad88-bffe-4964-88f5-1850bfd87fea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otp-code']</value>
      <webElementGuid>42f19142-6c2b-4cff-8a52-d396c0e0e9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='otp-form']/div/div/div/div/input</value>
      <webElementGuid>80079dde-0201-4f24-b993-a53bea32680c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/div/div/div/input</value>
      <webElementGuid>8bee5259-6d14-41ca-878d-7579875055ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'otp-code' and @placeholder = 'Enter OTP']</value>
      <webElementGuid>360505c7-3d1c-4fa0-ab52-18d03aa0f00f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
