<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_On Checker Approve</name>
   <tag></tag>
   <elementGuidId>3a51e2e3-4e70-462c-a8e7-16e1511fcc5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/section[2]/div/div[2]/div/div/div/div[2]/table/tbody/tr/td[14]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ddc41c4-a4f1-4776-a78f-36db38e0a856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center h-6 w-8 border rounded text-success-70 border-success-70 bg-white hover:bg-success-95 active:bg-success-90 mx-1</value>
      <webElementGuid>b127e76a-3bb7-41ad-88fc-27b76426deb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;mt-16 w-full overflow-x-hidden md:ml-64  ml-0 min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/section[@class=&quot;mt-6&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md&quot;]/div[@class=&quot;grid grid-cols-1 gap-6&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md&quot;]/div[@class=&quot;w-full overflow-x-auto&quot;]/div[1]/div[@class=&quot;overflow-x-auto&quot;]/table[@class=&quot;w-full table-fixed&quot;]/tbody[@class=&quot;relative table-fixed&quot;]/tr[@class=&quot;odd:bg-white even:bg-primary-99 border border-t-0 border-neutral-70&quot;]/td[@class=&quot;py-3 px-4 text-[0.8125rem] font-normal leading-4 !border-r-0 !border-l-0 border-r-neutral-70 last:border-r-0 align-top text-ellipsis overflow-hidden whitespace-nowrap align-middle&quot;]/div[@class=&quot;flex justify-between&quot;]/div[1]/button[@class=&quot;inline-flex items-center justify-center h-6 w-8 border rounded text-success-70 border-success-70 bg-white hover:bg-success-95 active:bg-success-90 mx-1&quot;]</value>
      <webElementGuid>8b0b3f47-5b68-4ade-b498-e74c57a42455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/section[2]/div/div[2]/div/div/div/div[2]/table/tbody/tr/td[14]/div/div/button</value>
      <webElementGuid>5bc70d84-974a-4680-8578-298ac795a115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Checker'])[1]/following::button[1]</value>
      <webElementGuid>c79a75e6-5804-4944-af36-cb9d688da3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CU_ROSNEFT_M'])[1]/following::button[1]</value>
      <webElementGuid>fca9568b-01be-4eba-8fa5-f70a5635ab6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SWF1675817961'])[2]/preceding::button[3]</value>
      <webElementGuid>c094bf85-affa-449b-b1cb-88b57199177c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New baru'])[1]/preceding::button[3]</value>
      <webElementGuid>2575a3df-e72b-4873-8185-664c13442e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/div/div/button</value>
      <webElementGuid>456d1479-292b-4efa-932f-7f4adfa07231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
