<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rejected Filter</name>
   <tag></tag>
   <elementGuidId>037be3f7-7873-4a49-b08d-02f640d3acd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'react-select-12-option-4' or (text() = 'Rejected' or . = 'Rejected')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ddbac985-dbae-4713-8eec-6d42dd2d069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>871b4aea-a631-4737-8e6e-7f1a67926512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d577adb6-6854-4796-a7ca-f8fbaa8b3e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-12-option-3</value>
      <webElementGuid>8a2d878a-18bd-4ba7-8e5c-ba3d451439af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0e5e8b84-d0da-4f0d-893e-3051bf2dc709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending</value>
      <webElementGuid>82c62747-94b9-46b8-bbd9-312ffa4e17bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;react-select-12-option-3&quot;]</value>
      <webElementGuid>d7cdac92-5335-4a52-87a6-694401d13131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-12-option-3' and (text() = 'Pending' or . = 'Pending')]</value>
      <webElementGuid>bd3ea90b-feeb-4257-b3b0-3e4eeb4335a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
