<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Beneficiary Email (Optional)</name>
   <tag></tag>
   <elementGuidId>e7cfae42-535c-4e7f-8d5c-d7ab9259f4c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div[1]/div[7]/div[2]/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2e8fed9-3f88-40d3-a5b6-3d93bd95f1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa2b7091-c683-402a-9103-e4d382cc766c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white border-neutral-70 hover:border-primary-70 focus:border-primary-70</value>
      <webElementGuid>db5e78e3-5d83-4a2b-a64c-d54b8d2b829a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>johndoe@gmail.com</value>
      <webElementGuid>a36f4eed-bfd8-484f-9c26-03af766a169a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;mt-16 w-full overflow-x-hidden md:ml-64  ml-0 min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;grid grid-rows-1 gap-4 mb-24&quot;]/div[@class=&quot;grid grid-cols-12 gap-2 mt-2&quot;]/div[@class=&quot;col-span-12&quot;]/div[@class=&quot;border border-white bg-white w-full h-full p-5 rounded-lg&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col space-y-5 w-1/2&quot;]/div[@class=&quot;flex flex-col space-y-3&quot;]/div[@class=&quot;flex spacx-x-2&quot;]/div[@class=&quot;flex flex-col space-y-2&quot;]/div[@class=&quot;flex space-x-2&quot;]/div[@class=&quot;relative inline-block&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white border-neutral-70 hover:border-primary-70 focus:border-primary-70&quot;]</value>
      <webElementGuid>98d684ad-54b8-412a-9a4a-abef71a4cd51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[5]</value>
      <webElementGuid>12472905-6ea2-4517-b965-0d78442d939a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div/div[8]/div/div/div/div/div/input</value>
      <webElementGuid>30594510-0eab-4834-ac9a-14637a948578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/input</value>
      <webElementGuid>ceebb8f4-584d-4db1-8c9d-a372e56c2f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'johndoe@gmail.com']</value>
      <webElementGuid>2f76b9c2-1036-4f60-aa16-be80a855c35e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
