<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>0846f516-1ca1-4bec-8b59-deb20bee732d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b4ed458-f16a-4d19-a2fd-5a18128b3d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>13f87523-228f-4950-8ee9-07c4303b0d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> focus:ring-1 hover:ring-primary-70  focus:ring-primary-70 focus:border-primary-70  block sm:text-sm border-neutral-70 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed</value>
      <webElementGuid>02507de5-de08-4ce2-9e81-f097a87a3e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>******</value>
      <webElementGuid>1fdf3e29-4324-49fc-9a73-a76b4a2be481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex h-screen w-full flex-col items-center justify-center overflow-y-auto bg-primary-50 p-4&quot;]/div[@class=&quot;mx-auto h-[424px] w-full rounded bg-white px-8 py-8 shadow-md sm:w-96&quot;]/form[1]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-1 hover:ring-primary-70  focus:ring-primary-70 focus:border-primary-70  block sm:text-sm border-neutral-70 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed&quot;]</value>
      <webElementGuid>cf9618a8-6afa-48e4-8f10-7d3a05576e5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>968f5d73-27d2-4ea9-bb1e-ebf2654b5758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/form/div[2]/div/input</value>
      <webElementGuid>4685563c-5639-42eb-b293-f01fe01d90aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a865ce88-c3da-4e37-86cd-ab4317189f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '******']</value>
      <webElementGuid>37b6baaf-b3b5-4ad9-912c-dacba907e95f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
