<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PasswordAddson</name>
   <tag></tag>
   <elementGuidId>cb296829-bbbb-4847-b87a-6b471bfe6767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'password' and @placeholder = '******']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c654d48-040a-4338-8439-ab3c892550b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3709b61d-9497-4dd5-b98c-f5e05e3dd40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> focus:ring-1 hover:ring-primary-70  focus:ring-primary-70 focus:border-primary-70  block sm:text-sm border-neutral-70 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed</value>
      <webElementGuid>c804e12d-32e9-486d-975c-4022480ef83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>******</value>
      <webElementGuid>3ce50fbb-ecf7-4756-9520-5918791923f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex h-screen w-full flex-col items-center justify-center overflow-y-auto bg-primary-50 p-4&quot;]/div[@class=&quot;mx-auto h-[424px] w-full rounded bg-white px-8 py-8 shadow-md sm:w-96&quot;]/form[1]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-1 hover:ring-primary-70  focus:ring-primary-70 focus:border-primary-70  block sm:text-sm border-neutral-70 border shadow-sm px-2 h-8 text-neutral-10 caret-primary-70 rounded w-full hover:outline-offset-0 disabled:bg-grey-90 disabled:cursor-not-allowed&quot;]</value>
      <webElementGuid>c9d065ae-e385-4344-a4ca-ef844f8b7ab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '******']</value>
      <webElementGuid>089a3af4-2a3e-4f81-85a7-c96d8569cb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>597052d1-c743-4070-94c9-3320dd3f683c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>4001cdfb-6473-4499-941f-001694c4dfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a5fe5672-5984-4d28-ad87-81bd588895e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
