<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukan OTP</name>
   <tag></tag>
   <elementGuidId>573e7b01-dfba-4533-9620-50ea440eaa81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otp-code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otp-code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb9bb833-c3b2-48a6-9e84-060ed08f69f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a2bcafaf-c73d-418d-885e-5ee3b7059f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white pr-8 border-neutral-70 hover:border-primary-70 focus:border-primary-70 h-auto text-sm hover:border-primary-70 focus:border-primary-70 border-neutral-70 w-full</value>
      <webElementGuid>3ee53232-013b-40de-a09b-1974ce9ebaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>402d0972-45e1-4c75-ba1c-066925d0a7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>otp-code</value>
      <webElementGuid>ea605aff-66e9-47c0-be76-fb9ba74c9d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp-code</value>
      <webElementGuid>47e2e482-674c-4e1c-9482-0e2dfa34599c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter OTP</value>
      <webElementGuid>eceb407c-2105-48b4-a35d-8000bddb38d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4c9a1854-1008-40ba-9026-890f1a415356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f176085-3382-4b2e-a7c9-f7d5faaec642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-form&quot;)/div[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;w-3/5 flex-col&quot;]/div[@class=&quot;relative inline-block w-full&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white pr-8 border-neutral-70 hover:border-primary-70 focus:border-primary-70 h-auto text-sm hover:border-primary-70 focus:border-primary-70 border-neutral-70 w-full&quot;]</value>
      <webElementGuid>afdc7f04-26ee-474b-9aed-868fa54a0d6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otp-code']</value>
      <webElementGuid>6da85806-a64e-42b4-bdae-78848d721bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='otp-form']/div/div/div/div/input</value>
      <webElementGuid>b1c069ad-b473-4fe8-8765-cb01a070b3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/div/div/div/input</value>
      <webElementGuid>557f58ba-a68d-493d-9ff5-fb4a3f55430a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'otp-code' and @placeholder = 'Enter OTP']</value>
      <webElementGuid>77f8a176-2d0c-4494-8220-f5df0bbbeca6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
