<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Due Date</name>
   <tag></tag>
   <elementGuidId>dc69521d-9e5e-485c-9e04-9b29359f6be5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='02/03/2023']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a406e10-209b-4c2f-b4ae-db174c40725e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>280eec92-e71d-48c1-9fbe-61141686410f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>bc91c4d7-7c44-4da4-8e58-411549e254c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-[38px] text-sm p-1 px-2 border border-grey-80 shadow-sm rounded </value>
      <webElementGuid>951275ed-16a5-4591-a4fa-b0ed4e7f9cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>02/03/2023</value>
      <webElementGuid>a08597fe-491f-4e63-8036-904757db10c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;relative w-full overflow-x-hidden md:ml-64  top-16 ml-0 h-[calc(100vh-64px)] bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;mb-22 flex flex-col&quot;]/div[@class=&quot;grid grid-cols-12 gap-3&quot;]/div[@class=&quot;col-span-4 h-full w-full rounded bg-white p-8 shadow-md&quot;]/form[1]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[1]/div[@class=&quot;flex flex-col space-y-5 pb-4&quot;]/div[4]/div[@class=&quot;react-datepicker-wrapper w-full&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/input[@class=&quot;w-full h-[38px] text-sm p-1 px-2 border border-grey-80 shadow-sm rounded&quot;]</value>
      <webElementGuid>b00ab794-ff51-440a-991b-d57b0d065da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='02/03/2023']</value>
      <webElementGuid>69f3493e-84cf-4c9f-9247-c6e2269238ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[2]/div[2]/form/div/div[2]/div/div/div[4]/div/div/input</value>
      <webElementGuid>3f8c22ba-318a-4631-bfa8-8cae7e470544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>1d3cadac-7f31-4c67-a6ff-92265b471b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>274a2ac2-685d-4148-8712-db7d504bf94d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
