<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DEDY YUSUF SILABAN - 037901005847535</name>
   <tag></tag>
   <elementGuidId>57003a10-5396-4fc1-90da-0359f03f9d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-senderAccountNumber-option-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-senderAccountNumber-option-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa06243a-7f2a-48c2-9ec0-3988b28ffae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>04949c66-dfda-4f60-a2db-b2a24fd28e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cd846f5-10a0-4c79-8072-97eb1a692bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-senderAccountNumber-option-6</value>
      <webElementGuid>1d6b3068-4a41-4541-95d6-0dcc6b4da8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>060bdfd4-6d52-4a44-ae76-407a971da640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DEDY YUSUF SILABAN - 037901005847535</value>
      <webElementGuid>8f289aa2-4b08-468d-94c4-6d8a2dc2e434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-senderAccountNumber-option-6&quot;)</value>
      <webElementGuid>c0b182d6-6bd5-4729-a2ae-290095bc6efe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-senderAccountNumber-option-6']</value>
      <webElementGuid>4729e230-5ae7-4748-93bb-8ff04698f3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-senderAccountNumber-listbox']/div/div[7]</value>
      <webElementGuid>d5b70f40-b849-4f48-bf42-38ebf03adc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUTIARA AGHNYN AISYA - 001201182874500'])[1]/following::div[1]</value>
      <webElementGuid>ae0c9515-042c-4b9d-99fc-7e6e046b3375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANGGA FITHRA WARDHAN - 020603000001509'])[1]/following::div[2]</value>
      <webElementGuid>f8bebf7c-e42c-477d-85ea-e2d6dcdad853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INTERFERRO MANGANDO - 020602000029307'])[1]/preceding::div[1]</value>
      <webElementGuid>a74746d8-f0f4-4596-8f13-deecc18264e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LARASATI DIAH INDRIA - 001201183100506'])[1]/preceding::div[2]</value>
      <webElementGuid>ba2d949c-8cfd-417b-8abc-0fcfa3604208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DEDY YUSUF SILABAN - 037901005847535']/parent::*</value>
      <webElementGuid>10262c89-6886-418a-b4a1-a991bbbded62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[7]</value>
      <webElementGuid>f183ce75-a816-4e76-9fb9-4abe24c0a6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-senderAccountNumber-option-6' and (text() = 'DEDY YUSUF SILABAN - 037901005847535' or . = 'DEDY YUSUF SILABAN - 037901005847535')]</value>
      <webElementGuid>dcfb4a12-12cb-484e-9b5a-b222026638e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
