<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Beneficiary Account Number_receiverAccountNumber</name>
   <tag></tag>
   <elementGuidId>e0ff1d2a-c808-426c-98a1-6a71189f0727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='receiverAccountNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;receiverAccountNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37f69d6b-63df-443e-90c7-689f8661f32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcd3c743-6aec-4e2a-b060-0fe3721c0a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white border-neutral-70 hover:border-primary-70 focus:border-primary-70 h-auto text-sm hover:border-primary-70 focus:border-primary-70 border-neutral-70 w-full</value>
      <webElementGuid>73d791a6-f123-483e-a6e4-a93367dd9b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>c88e907b-7778-4d53-9334-f9e139ddb67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>receiverAccountNumber</value>
      <webElementGuid>c85e2909-6c44-4d8c-8163-9584af42cb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Beneficicary Account Number</value>
      <webElementGuid>57d74ea3-d5df-4b7a-9430-b4733e93cb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>2b3bf455-c13a-4fd7-9664-dee25303fa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;relative w-full overflow-x-hidden md:ml-64  ml-0 h-[calc(100vh-64px)] top-16 bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/div[@class=&quot;relative&quot;]/section[@class=&quot;space-y-6&quot;]/div[2]/form[1]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md flex flex-col divide-y divide-[#E0E0E0]&quot;]/div[@class=&quot;w-full space-y-4 py-3.5 2xl:w-2/3&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex w-full space-x-4&quot;]/div[@class=&quot;relative inline-block w-full&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;focus:ring-0.5 block h-8 w-full rounded px-2 text-[0.8125rem] caret-primary-70 shadow-sm transition-all placeholder:text-neutral-40 focus:outline-0 focus:ring-primary-70 bg-white border-neutral-70 hover:border-primary-70 focus:border-primary-70 h-auto text-sm hover:border-primary-70 focus:border-primary-70 border-neutral-70 w-full&quot;]</value>
      <webElementGuid>6cb356b0-6a42-4499-b7f9-ab94eb7a6250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='receiverAccountNumber']</value>
      <webElementGuid>d38bdf8b-3f14-427e-b524-84720e1678e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/section/div[2]/form/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>471b86b2-37a8-46d4-9683-467288b4431f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>44180c0f-7eff-42af-a599-26dc9021f932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'receiverAccountNumber' and @placeholder = 'Enter Beneficicary Account Number']</value>
      <webElementGuid>a2750325-e77f-4c9b-8372-2a2bbb2ac5c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
