<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BRI to Other Bank</name>
   <tag></tag>
   <elementGuidId>d4dd6be9-6733-4479-846d-f62bbcd59d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-disclosure-button-:rl:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8dd244f-e2cc-4967-877b-2a0c8a1e06e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-disclosure-button-:rl:</value>
      <webElementGuid>06fb4363-3489-4014-88e0-7fb462511a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white hover:bg-primary-50  hover:bg-opacity-40 hover:text-secondary-70 mt-1 flex h-12 items-center justify-between text-xs hover:pl-1 md:w-full</value>
      <webElementGuid>00d885dc-0277-4623-8c99-1896955e4304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9059aab-5f22-40df-9a04-c4ae475cfaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39a13de8-3f83-4f1b-aea2-874de814b1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BRI to Other Bank</value>
      <webElementGuid>717c1894-0a1e-436d-8b44-78c531bbffc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-disclosure-button-:rl:&quot;)</value>
      <webElementGuid>a54dd809-e297-4723-9846-d123808f56ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-disclosure-button-:rl:']</value>
      <webElementGuid>31061445-41ad-41d6-9421-41094e0d69bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='disclosureSideBar']/dt/button)[5]</value>
      <webElementGuid>7cf8392d-2854-45ce-9f4c-9f303418b588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fund Transfer'])[2]/following::button[2]</value>
      <webElementGuid>8e6dd866-0447-4ec5-a701-0badddb736b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Action'])[1]/preceding::button[1]</value>
      <webElementGuid>c11667e3-81e6-4bd3-8f57-97a197b12920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/dt/button</value>
      <webElementGuid>1b84cf84-f099-4da6-8e7e-0a0ed9dc35e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-disclosure-button-:rl:' and @type = 'button' and (text() = ' BRI to Other Bank' or . = ' BRI to Other Bank')]</value>
      <webElementGuid>93cf8879-82ea-4657-b458-2c9ef720411b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
