<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_option ZWL focused, 1 of 157. 157 resul_a8cca0</name>
   <tag></tag>
   <elementGuidId>d6f63b92-76ba-4223-a8a9-9ee051234c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/section[2]/div/div[2]/div/div/div/form/div/div/div[7]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ddc7f18-fe11-4181-a7ac-84efaf8ed6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__container css-b62m3t-container</value>
      <webElementGuid>ea545e51-15a5-4b65-a726-a2ed9ab49625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>option ZWL focused, 1 of 157. 157 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Select...ZWLZMWYERMADXPFUSDVNDVEFEURVUVUZSUYUGBPAEDUGXAUDTMTTRYTNDTTDTOPNZDXOFTHBTZSTJSTWDSYPCHFSEKSZLNOKSRDSDGLKRSSPKRWZARSOSSBDANGSGDSLLSCRRSDSARSTDWSTXCDSHPRWFRONQARPLNPHPPENPYGPGKPABPKROMRKPWNGNNIONPRNADMMKMZNMNTMDLMXNMURMROMVRMYRMWKMGAMOPLYDLRDLSLLBPLAKKGSKWDKESKZTJODJEP�(JJPYJMDILSIMPIQDIRRIDRINRISKHUFHKDHNLHTGGYDGNFGGPGTQDKKGIPGHSGELGMDXAFFJDFKPETBERNSVCEGPDOPDJFCDFCZKCUPHRKCRCKMFCOPCNYCLPKYDCVECADKHRBIFBGNBNDBRLBWPBAMBOBBTNBMDBZDBYRBBDBDTBHDBSDAZNAWGAMDARSAOADZDALLAFN</value>
      <webElementGuid>a7e8e778-c8a7-4391-82ae-b20189770700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;mt-16 w-full overflow-x-hidden md:ml-64  ml-0 min-h-screen bg-neutral-90&quot;]/div[@class=&quot;flex-1&quot;]/main[@class=&quot;layout-container px-4 py-8 sm:px-6 md:px-8&quot;]/section[@class=&quot;mt-6&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md&quot;]/div[@class=&quot;grid grid-cols-1 gap-6&quot;]/div[@class=&quot;bg-white p-8 rounded drop-shadow-md&quot;]/div[@class=&quot;w-full overflow-x-auto&quot;]/div[1]/form[1]/div[@class=&quot;bg-primary-99 rounded border border-grey-80 p-4 mb-6&quot;]/div[@class=&quot;grid grid-cols-2 gap-4 md:grid-cols-4&quot;]/div[@class=&quot;relative inline-block&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;react-select__container css-b62m3t-container&quot;]</value>
      <webElementGuid>ec459b32-fdfa-4469-9b7e-a1fe9a433064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/section[2]/div/div[2]/div/div/div/form/div/div/div[7]/div/div</value>
      <webElementGuid>e406cdda-9c12-4ab4-817e-a96bf871f7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::div[2]</value>
      <webElementGuid>00453986-9f7c-4254-9bd5-e8792e1c19dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/following::div[5]</value>
      <webElementGuid>0d1d307c-3c59-42f6-ac2f-aa22f049e6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div</value>
      <webElementGuid>429d661c-988e-4d92-a42e-3da0c2f43333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'option ZWL focused, 1 of 157. 157 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Select...ZWLZMWYERMADXPFUSDVNDVEFEURVUVUZSUYUGBPAEDUGXAUDTMTTRYTNDTTDTOPNZDXOFTHBTZSTJSTWDSYPCHFSEKSZLNOKSRDSDGLKRSSPKRWZARSOSSBDANGSGDSLLSCRRSDSARSTDWSTXCDSHPRWFRONQARPLNPHPPENPYGPGKPABPKROMRKPWNGNNIONPRNADMMKMZNMNTMDLMXNMURMROMVRMYRMWKMGAMOPLYDLRDLSLLBPLAKKGSKWDKESKZTJODJEP�(JJPYJMDILSIMPIQDIRRIDRINRISKHUFHKDHNLHTGGYDGNFGGPGTQDKKGIPGHSGELGMDXAFFJDFKPETBERNSVCEGPDOPDJFCDFCZKCUPHRKCRCKMFCOPCNYCLPKYDCVECADKHRBIFBGNBNDBRLBWPBAMBOBBTNBMDBZDBYRBBDBDTBHDBSDAZNAWGAMDARSAOADZDALLAFN' or . = 'option ZWL focused, 1 of 157. 157 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Select...ZWLZMWYERMADXPFUSDVNDVEFEURVUVUZSUYUGBPAEDUGXAUDTMTTRYTNDTTDTOPNZDXOFTHBTZSTJSTWDSYPCHFSEKSZLNOKSRDSDGLKRSSPKRWZARSOSSBDANGSGDSLLSCRRSDSARSTDWSTXCDSHPRWFRONQARPLNPHPPENPYGPGKPABPKROMRKPWNGNNIONPRNADMMKMZNMNTMDLMXNMURMROMVRMYRMWKMGAMOPLYDLRDLSLLBPLAKKGSKWDKESKZTJODJEP�(JJPYJMDILSIMPIQDIRRIDRINRISKHUFHKDHNLHTGGYDGNFGGPGTQDKKGIPGHSGELGMDXAFFJDFKPETBERNSVCEGPDOPDJFCDFCZKCUPHRKCRCKMFCOPCNYCLPKYDCVECADKHRBIFBGNBNDBRLBWPBAMBOBBTNBMDBZDBYRBBDBDTBHDBSDAZNAWGAMDARSAOADZDALLAFN')]</value>
      <webElementGuid>71b9e177-0c04-4677-8ada-0d58b1c36f15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
