<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Beneficiary Bank_</name>
   <tag></tag>
   <elementGuidId>690362f2-d8a2-450d-9ce2-9f60552a9804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div[3]/div/main/section[2]/div/div[2]/div/div/div/form/div/div[1]/div[2]/div/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'headlessui-combobox-input-:r2q:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e98c9dc6-8a07-4632-9554-d69ca9a0a368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white block w-full border-neutral-70 text-[0.8125rem] h-8 px-2 rounded transition-all caret-primary-70 placeholder:text-neutral-40 focus:ring-0.5 focus:ring-primary-70 focus:outline-0 shadow-sm hover:border-primary-70 focus:border-primary-70 disabled:bg-grey-90 disabled:cursor-not-allowed</value>
      <webElementGuid>c519903c-93ba-462d-a560-d76fdcc02b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-:r2q:</value>
      <webElementGuid>2ed0638f-a9b7-43e8-854b-ea0570ada497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>c89c1d20-2f70-4c11-b38f-e3075b8a0a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71dfc762-89b1-4d91-b31a-6be327ff4d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5b0c72a1-2f80-4366-9e2e-4d930c85cc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-:r14:&quot;)</value>
      <webElementGuid>118e06ed-b723-4e5b-ad8e-0e50e29c6c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'headlessui-combobox-input-:r2q:']</value>
      <webElementGuid>d6ffb2cc-288c-4c4c-85c7-3a8316584b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/section[2]/div/div[2]/div/div/div/form/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>dd641a85-789b-48e3-8c55-360efaed0b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>4362584f-0be2-43b3-a0bf-378a3b4b4335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-:r14:' and @type = 'text']</value>
      <webElementGuid>586fb6df-2a40-4be9-9c19-7d613ba75288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
