<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank CodeSWIFT Code_headlessui-combobox-input-rp</name>
   <tag></tag>
   <elementGuidId>fda643af-be0f-4357-8e78-85fd67e0edd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-:rp:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bab44477-c6f9-4a67-aa93-7facc6b1917d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white block w-full border-neutral-70 text-[0.8125rem] h-8 px-2 rounded transition-all caret-primary-70 placeholder:text-neutral-40 focus:ring-0.5 focus:ring-primary-70 focus:outline-0 shadow-sm hover:border-primary-70 focus:border-primary-70 disabled:bg-grey-90 disabled:cursor-not-allowed</value>
      <webElementGuid>c3672f2f-9bfb-4c52-8610-83e88eaafba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-:rp:</value>
      <webElementGuid>a8322bd9-b184-4365-933e-c2e0c677c92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>529b085f-a201-48ed-bee8-c4006610aff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a89c033-00a8-4738-b544-3a92b8f86cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>decec1d1-04ae-48e7-a81d-b64b37a58506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>26cc1f37-ca40-4332-81ed-cebbfb821b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>headlessui-combobox-options-:rr:</value>
      <webElementGuid>f87f1cc9-e722-4a85-b2cc-60dc9f1af9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-:rp:&quot;)</value>
      <webElementGuid>d5f004bb-7fb5-435f-9526-feb57aa1d11a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-:rp:']</value>
      <webElementGuid>a8a6eb68-3220-4e0c-8540-0508cfbb6123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/main/div/div[3]/div/div/div/div/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>2c5cfdf6-88bf-4260-a3e8-a879b9fc7142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/input</value>
      <webElementGuid>12ca708a-4a62-445b-aab9-1ed57c380330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'headlessui-combobox-input-:rp:' and @type = 'text']</value>
      <webElementGuid>8e947062-c27f-4205-a2c5-f5e273a0f011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
