<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Swift_Swift</name>
   <tag></tag>
   <elementGuidId>95b83e8e-22f0-402d-9906-f5803be5c677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Swift']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Swift&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0055fa1c-279b-4a9c-889d-bc41e77e65dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>5e252ac2-a4d2-4bbc-9bea-b367b75c7823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9462a389-2016-4c6c-82a7-c486dd8825af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Swift</value>
      <webElementGuid>83d9f93d-07fa-476d-8908-eebca23dc8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-:r49:&quot;)/div[@class=&quot;absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 min-w-120 bg-white p-8 shadow-md rounded text-sm w-max opacity-100 scale-100&quot;]/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/div[@class=&quot;h-32 w-64 rounded border p-4 flex cursor-pointer flex-col justify-between border-grey-70&quot;]/div[@class=&quot;ite flex justify-between&quot;]/input[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>45125ea3-c3e3-4c29-aac7-cd99a7e41092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Swift']</value>
      <webElementGuid>229cd06e-4a01-423a-9076-09cd4d6038df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-:r49:']/div[2]/div[5]/div[2]/div/input</value>
      <webElementGuid>0c8d169c-2e0e-4972-8508-3eaac488042b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>a77d6a03-6de3-4a38-b665-29047a97fa87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Swift']</value>
      <webElementGuid>d063fe27-3271-4c2c-adfe-33e44c0f8c15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
